/**
 * dsh-notch — vendor the idle mascot engine.
 *
 * The upstream OpenBotMotion engine (tools/idle/) is a browser UMD bundle, and
 * the nine idle motions live in a second browser script that installs
 * \`window.poseFor\`. Neither is importable: the UMD would take its
 * \`module.exports\` branch inside esbuild's CJS wrapper and clobber the client
 * bundle's exports, and the motions script is written for a <script> tag.
 *
 * This script converts both into plain ESM modules under src/vendor/. The
 * upstream files stay the source of truth; re-run after updating them:
 *
 *   node scripts/vendor-idle.mjs
 *
 * Generated output IS committed (see src/vendor/*.js) so build.mjs needs no
 * dependency on tools/, which the published package does not ship.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(HERE, '..')
const OUT = resolve(ROOT, 'src/vendor')

const NOTICE = [
  '/*',
  ' * GENERATED by scripts/vendor-idle.mjs — do not edit by hand.',
  ' *',
  ' * Source: tools/idle/renderer.js (OpenBotMotion v1.0.0)',
  ' * Upstream: https://github.com/aa2246740/open-bot-motion',
  ' * License: MIT — full text in LICENSE.open-bot-motion (shipped),',
  ' *           upstream copy at tools/idle/LICENSE.open-bot-motion',
  ' */',
  '',
].join('\n')

// ---- 1. the engine: UMD -> ESM default export --------------------------------
const renderer = readFileSync(resolve(ROOT, 'tools/idle/renderer.js'), 'utf8')

const HEAD = '}(typeof self !== \'undefined\' ? self : this, function () {'
const headIndex = renderer.indexOf(HEAD)
if (headIndex < 0) throw new Error('vendor-idle: UMD head marker not found in renderer.js')

const tail = '}));'
const tailIndex = renderer.lastIndexOf(tail)
if (tailIndex < 0) throw new Error('vendor-idle: UMD tail marker not found in renderer.js')

// Everything between the UMD head and tail is the factory body, including
// \`'use strict';\` and the trailing \`return { ... };\`.
const engineBody = renderer.slice(headIndex + HEAD.length, tailIndex)

const engine =
  NOTICE
  + 'const OpenBotMotion = (function () {\n'
  + engineBody.replace(/\s+$/, '')
  + '\n})()\n\n'
  + 'export default OpenBotMotion\n'

// ---- 2. the motions: window.poseFor -> named ESM export ----------------------
const motions = readFileSync(resolve(ROOT, 'tools/idle/motions.js'), 'utf8')

const helperStart = motions.indexOf('const clamp=')
if (helperStart < 0) throw new Error('vendor-idle: helper block not found in motions.js')
const demoStart = motions.indexOf('const items=')
if (demoStart < 0) throw new Error('vendor-idle: demo block not found in motions.js')

const poseBlock = motions.slice(helperStart, demoStart)
const ASSIGN = 'window.poseFor=(id,time)=>{'
if (!poseBlock.includes(ASSIGN)) throw new Error('vendor-idle: window.poseFor assignment not found')

const motionsModule =
  NOTICE
  + "import OpenBotMotion from './open-bot-motion.js'\n\n"
  + poseBlock.replace(ASSIGN, 'export function poseFor(id, time) {').replace(/\s+$/, '')
  + '\n'

mkdirSync(OUT, { recursive: true })
writeFileSync(resolve(OUT, 'open-bot-motion.js'), engine, 'utf8')
writeFileSync(resolve(OUT, 'idle-motions.js'), motionsModule, 'utf8')

console.log('[vendor-idle] open-bot-motion.js  ' + engine.length + ' bytes')
console.log('[vendor-idle] idle-motions.js     ' + motionsModule.length + ' bytes')
